// <auto-generated />
namespace ForumTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FORUMTEST : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FORUMTEST));
        
        string IMigrationMetadata.Id
        {
            get { return "202102131256329_FORUMTEST"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
