// <auto-generated />
namespace ForumTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FORUM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FORUM));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181336073_FORUM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
